#! /bin/sh


picom -b --experimental-backends &
nitrogen --restore &
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
bspc config focus_follows_pointer true
dunst &
#xsetroot -cursor_name breeze_cursors
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI

bspc config window_gap					 0	
bspc config border_width         2
bspc config split_ratio          0.52
bspc config active_border_color	"#D8DEE9" 
#bspc config gapless_monocle true
bspc config single_monocle true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"


bspc rule -a Spotify desktop='^4'
bspc rule -a Discord desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
