#! /bin/sh


picom -b --experimental-backends &
nitrogen --restore &
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
bspc config focus_follows_pointer true
dunst &
#xsetroot -cursor_name breeze_cursors
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6 

bspc config ignore_ewmh_focus true
bspc config window_gap					 0	
bspc config border_width         2
bspc config split_ratio          0.50
bspc config active_border_color	"#D8DEE9" 
bspc config borderless_monocle   true
bspc config single_monocle      true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config top_padding 26
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"


bspc rule -a Spotify desktop='^4'
bspc rule -a firefox:Browser:'About Mozilla Firefox' state=floating
bspc rule -a discord desktop='3' follow=off focus=off
